version: 2
updates:
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: monthly
    time: "06:00"
    timezone: UTC
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
    time: "05:45"
    timezone: UTC
